<?php

return [

    'pages' => [

        'figma-comments' => [
            'slug' => 'figma-comments',
            'path' => '/alternatives/figma-comments',
            'label' => 'Figma comments',
            'competitor' => 'Figma comments',
            'competitor_link' => 'Figma',
            'competitor_url' => 'https://www.figma.com',
            'teaser' => 'Design-file critique vs agent-built UI that needs a ship loop.',
            'icon' => 'figma',
            'title' => 'Best Figma comments alternative for agent design checkups — ReviseMy',
            'description' => 'Looking for a Figma comments alternative when an AI agent ships the UI? ReviseMy gives humans authoritative marks on captures, a board, and structured next steps back over MCP — without replacing Figma for design files.',
            'keywords' => [
                'Figma comments alternative',
                'design review for AI agents',
                'visual feedback MCP',
                'human in the loop UI review',
                'agent design checkup',
            ],
            'headline' => 'Best Figma comments alternative when your agent ships the UI',
            'subheadline' => 'Figma comments are excellent on design files. ReviseMy is for the pixels your agent actually built — marks that drive next_action, not another thread in the canvas.',
            'intro' => 'People search for a Figma comments alternative for different reasons: the UI already exists in staging or screenshots, the builder is a coding agent that needs structured work packets, or design-file comments never map cleanly to “what to change next” in the repo. Figma remains the right place to critique components and systems in the design file. ReviseMy is the stronger alternative when the real problem is human-in-the-loop review of agent-built UI — with authoritative marks, a status board, and MCP handoff — without asking everyone to live in Figma for every pass.',
            'why_look' => [
                'The screen already shipped from an agent — feedback belongs on the capture, not only on a Figma frame that may be out of date.',
                'You need a clear next_action for the agent (wait, apply marks, open another pass), not a comment that dies in a design tool.',
                'Reviewers should mark and approve without a Figma seat; guests leave suggestions without owning the decision.',
                'You want open → resolved → verified status across passes, with optional before/after evidence — not only “resolved” in a comment thread.',
            ],
            'what_to_look_for' => [
                'Whether feedback lives on design files or on the pixels the agent shipped',
                'Whether the agent can poll structured work packets over MCP (or REST)',
                'Whether human marks stay authoritative vs optional AI hints',
                'Whether multi-pass reviews stay scannable on a board',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Human-in-the-loop design checkup for AI agents. Capture UI, websites, email, or slides; mark with intent; track the board; send next_action back over MCP.',
                    'best_for' => 'Teams where an agent builds UI and a human must approve before the loop stops.',
                    'bullets' => [
                        'Authoritative rose marks → work_packets.pins',
                        'Board: open → resolved → verified',
                        'Second opinion stays suggestions only',
                        'Free try token — no account for reviewers',
                    ],
                ],
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Fast visual annotation on live sites and assets via a share link — strong for client proofing without an agent in the loop.',
                    'best_for' => 'Agency or client website QA when nobody needs MCP next_action.',
                    'bullets' => [
                        'Link-based annotation',
                        'Live site and asset markup',
                        'Client-friendly, low install friction',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Figma comments for design-system and file-level critique before anything is built.',
                'Use ReviseMy after the agent ships screenshots or a URL — marks map to code work, not to layers.',
                'You can run both: Figma for craft in the file, ReviseMy for the agent ship loop.',
                'If there is no coding agent and all work stays in Figma, stay in Figma.',
            ],
            'verdict' => 'Choose ReviseMy if an agent ships UI and you need human marks that drive the next pass over MCP. Choose Figma comments if the artifact is still the design file and the builder is a human in Figma — not an agent waiting on next_action.',
            'faq' => [
                [
                    'q' => 'Is ReviseMy a Figma replacement?',
                    'a' => 'No. ReviseMy does not replace Figma as a design tool. It is an alternative feedback surface when the thing to review is agent-built UI (screenshots, capture URL, PDF, HTML) and the consumer of feedback is an agent.',
                ],
                [
                    'q' => 'Can designers use ReviseMy without MCP?',
                    'a' => 'Yes. Reviewers only need the secret review link. MCP setup is for the person connecting the agent.',
                ],
                [
                    'q' => 'What about Figma Make or Dev Mode handoff?',
                    'a' => 'Those stay in the Figma ecosystem. ReviseMy starts when pixels exist outside the file and an agent needs structured marks to continue.',
                ],
            ],
            'related' => ['pastel', 'lucidly', 'ai-design-critique'],
        ],

        'marker-io' => [
            'slug' => 'marker-io',
            'path' => '/alternatives/marker-io',
            'label' => 'Marker.io',
            'competitor' => 'Marker.io',
            'competitor_link' => 'Marker.io',
            'competitor_url' => 'https://marker.io',
            'teaser' => 'Website bug reports to PM tools vs an agent that owns the fix loop.',
            'icon' => 'marker-io',
            'title' => 'Best Marker.io alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Marker.io alternative when a coding agent should fix what you marked? ReviseMy turns human marks into MCP work packets and a verification board — without replacing Marker for classic website bug reporting into Jira or Linear.',
            'keywords' => [
                'Marker.io alternative',
                'website annotation alternative',
                'visual bug report MCP',
                'AI agent design feedback',
                'human in the loop QA',
            ],
            'headline' => 'Best Marker.io alternative when the fixer is an agent',
            'subheadline' => 'Marker.io shines at capturing live-site bugs with browser context into your PM stack. ReviseMy is for when the implementer is an AI agent that needs next_action — not another ticket queue.',
            'intro' => 'People look for a Marker.io alternative when tickets pile up, when the “developer” is a coding agent that never opens Jira, or when they want design intent (must-fix vs keep) and multi-pass verification — not only a screenshot-backed bug. Marker.io remains a strong fit for human QA teams filing into Linear, Jira, or Asana. ReviseMy is the stronger alternative when feedback must close the loop with an agent over MCP: mark on the capture, resolve with notes and after shots, verify on the board, approve or open the next pass.',
            'why_look' => [
                'The person fixing the UI is an agent that polls get_review — not a human watching a PM board.',
                'You need must-fix / nice to have / keep intent on the mark, not only a generic bug description.',
                'You want open → in progress → resolved → verified with before/after evidence across passes.',
                'Reviewers and guests should not need seats in a separate bug-reporting product.',
            ],
            'what_to_look_for' => [
                'Whether feedback feeds a PM tool or an agent MCP endpoint',
                'Whether “done” means ticket closed or human-verified on pixels',
                'Whether second-opinion AI hints stay non-authoritative',
                'Whether you review screenshots, URLs, email HTML, and slides — not only live sites',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Marks become work packets for your agent. The board tracks status until a human verifies. Optional vision hints never flip the decision.',
                    'best_for' => 'Agent-driven UI ship loops where humans still approve.',
                    'bullets' => [
                        'MCP create_review / get_review / resolve_marks',
                        'Owner board with verification gate',
                        'Guest links for non-authoritative suggestions',
                        'Webhook on review.decided for CI gates',
                    ],
                ],
                [
                    'id' => 'lucidly',
                    'label' => 'Lucidly',
                    'href' => '/alternatives/lucidly',
                    'badge' => null,
                    'summary' => 'Website QA with visual comments and a built-in Kanban — strong for agencies and clients without coding agents.',
                    'best_for' => 'Multi-client website proofing with task tracking in one place.',
                    'bullets' => [
                        'Comment on live/staging sites',
                        'Kanban from comments',
                        'Unlimited guests on the plan model',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Marker.io when human QA files bugs into Jira/Linear with browser metadata and nobody is running an agent loop.',
                'Use ReviseMy when the implementer is Cursor, Claude, Copilot, or similar and should follow next_action.',
                'A pragmatic split: Marker for classic production bug reports; ReviseMy for agent-built feature checkups.',
                'Do not force-fit Marker into an MCP agent workflow — the handoff shapes are different.',
            ],
            'verdict' => 'Choose ReviseMy if the fixer is an AI agent and you need marks, a verification board, and MCP next_action. Choose Marker.io if your workflow is human QA → ticket tracker and you do not need an agent design checkup loop.',
            'faq' => [
                [
                    'q' => 'Does ReviseMy replace Marker.io integrations?',
                    'a' => 'No. ReviseMy does not aim to be a Jira/Linear bug reporter. It hands structured work to agents. Keep Marker when PM-tool filing is the product.',
                ],
                [
                    'q' => 'Can ReviseMy capture a live URL?',
                    'a' => 'Yes — with capture_url and a public page_url (desktop + mobile). Localhost still needs screenshots or data URLs.',
                ],
                [
                    'q' => 'Who verifies fixes?',
                    'a' => 'Only humans verify on the board. Agents may resolve with notes and after images; they never flip verified.',
                ],
            ],
            'related' => ['pastel', 'lucidly', 'figma-comments'],
        ],

        'pastel' => [
            'slug' => 'pastel',
            'path' => '/alternatives/pastel',
            'label' => 'Pastel',
            'competitor' => 'Pastel',
            'competitor_link' => 'Pastel',
            'competitor_url' => 'https://usepastel.com',
            'teaser' => 'Fast client annotation links vs agent checkups with next_action.',
            'icon' => 'pastel',
            'title' => 'Best Pastel alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Pastel alternative when coding agents ship the UI? ReviseMy keeps client-friendly review links while giving agents MCP work packets, a verification board, and type-aware checkups — without replacing Pastel for agency proofing without agents.',
            'keywords' => [
                'Pastel alternative',
                'usepastel alternative',
                'website annotation alternative',
                'design review for AI agents',
                'visual feedback MCP',
            ],
            'headline' => 'Best Pastel alternative when an agent is in the loop',
            'subheadline' => 'Pastel makes share-a-link annotation feel instant for clients. ReviseMy keeps that link simplicity for reviewers — and adds the MCP ship loop Pastel was never built to own.',
            'intro' => 'People search for a Pastel alternative when client comments need to become agent work, when reviews include app screenshots or email HTML — not only live sites — or when “inbox zero” comments still leave the coding agent guessing. Pastel is excellent for low-friction visual feedback and approvals on websites and assets. ReviseMy is the stronger alternative when a human must mark intent on captures and an agent must follow next_action until approve — with a board that separates resolved from verified.',
            'why_look' => [
                'Comments need to become structured pins for an agent, not only export to a PM tool.',
                'You review agent UI, slides, or email HTML as often as live marketing sites.',
                'You want authoritative owner marks vs guest suggestions vs optional AI hints.',
                'Multi-pass agent work needs before/after evidence and human verification.',
            ],
            'what_to_look_for' => [
                'Share-link friction for non-technical reviewers',
                'Whether an agent can consume the feedback without a human retyping tickets',
                'Coverage beyond live websites (screenshots, PDF, HTML)',
                'Clear separation of suggestions vs decisions',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Secret review links for humans; MCP for agents. Same checkup loop across UI, websites, email, and slides.',
                    'best_for' => 'Teams shipping with coding agents who still want client or designer eyes on the pixels.',
                    'bullets' => [
                        'No account required for reviewers',
                        'Guest links for suggestions only',
                        'Board + resolve_marks for the agent',
                        'Connectors for ChatGPT, Claude, Copilot, Cursor, Grok',
                    ],
                ],
                [
                    'id' => 'marker-io',
                    'label' => 'Marker.io',
                    'href' => '/alternatives/marker-io',
                    'badge' => null,
                    'summary' => 'Live-site visual bug reporting with rich browser context into existing PM tools.',
                    'best_for' => 'Human QA → Jira/Linear without an agent loop.',
                    'bullets' => [
                        'Browser and technical metadata',
                        'PM tool destinations',
                        'Production bug reporting workflows',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Pastel for agency client proofing when there is no coding agent and speed-to-annotate is the whole product.',
                'Use ReviseMy when the next reader of feedback is an agent on MCP.',
                'You can keep Pastel for marketing-site client rounds and ReviseMy for agent-built product UI.',
                'If export-to-Asana/Jira is the success metric and agents are out of scope, Pastel (or Marker/Lucidly) may fit better.',
            ],
            'verdict' => 'Choose ReviseMy if reviewers need a simple link and agents need structured next_action. Choose Pastel if the workflow is human client annotation on sites/assets with no agent ship loop.',
            'faq' => [
                [
                    'q' => 'Is ReviseMy as easy for clients as Pastel?',
                    'a' => 'Reviewers open a secret link and mark — no MCP, no ReviseMy account. Guest links are suggestions-only. Setup complexity sits with the person connecting the agent.',
                ],
                [
                    'q' => 'Does ReviseMy annotate live DOM elements like Pastel?',
                    'a' => 'ReviseMy marks regions on captured screenshots (including URL capture). It is capture-based, not a live DOM overlay product.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Pastel for classic client website rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['lucidly', 'marker-io', 'figma-comments'],
        ],

        'lucidly' => [
            'slug' => 'lucidly',
            'path' => '/alternatives/lucidly',
            'label' => 'Lucidly',
            'competitor' => 'Lucidly',
            'competitor_link' => 'Lucidly',
            'competitor_url' => 'https://lucidly.so',
            'teaser' => 'Agency website QA + Kanban vs agent MCP checkup loops.',
            'icon' => 'lucidly',
            'title' => 'Best Lucidly alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Lucidly alternative when coding agents ship the work? ReviseMy pairs human marks and a verification board with MCP next_action — without replacing Lucidly for agency website QA and client Kanban workflows.',
            'keywords' => [
                'Lucidly alternative',
                'lucidly.so alternative',
                'website QA alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best Lucidly alternative when agents ship the site',
            'subheadline' => 'Lucidly organizes website QA comments into a Kanban for agencies and clients. ReviseMy organizes marks for an agent that must fix, prove, and wait for human verify.',
            'intro' => 'People look for a Lucidly alternative when the “dev team” is increasingly an AI agent, when feedback spans app UI and email — not only marketing sites — or when status needs a human verification gate after the agent claims done. Lucidly is a strong, focused website QA and collaboration product (comments, guests, Kanban). ReviseMy is the stronger alternative when the consumer of feedback is an agent over MCP and “done” means a human verified the pixels on the board — not only a card moved on a Kanban.',
            'why_look' => [
                'Implementers are agents that need resolve_marks and next_action, not only assigned Kanban cards.',
                'You need before/after evidence and human-only verified status.',
                'Checkups include screenshots, PDF slides, or email HTML as well as live URLs.',
                'You want second-opinion checklist/vision hints that never override human marks.',
            ],
            'what_to_look_for' => [
                'Agency client QA vs agent-native ship loops',
                'Kanban for humans vs board lifecycle for agent+human',
                'Seat/guest model vs secret review links + try tokens',
                'Whether MCP connectors matter more than unlimited collaborators',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Open-source human-in-the-loop design review for agents. Marks, board, second opinion, connectors — built for the MCP checkup loop.',
                    'best_for' => 'Product and eng teams (and agencies) where agents build and humans approve.',
                    'bullets' => [
                        'MCP Apps or review_url workflows',
                        'Owner board with verify gate',
                        'Type-aware checkups (UI, website, email, slides)',
                        'Guest suggestions without giving away authority',
                    ],
                ],
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Lightweight link-based annotation — a close peer when you want speed over Kanban depth.',
                    'best_for' => 'Fast client markup without a heavy QA suite.',
                    'bullets' => [
                        'Share-link collaboration',
                        'Live site and asset feedback',
                        'Low onboarding for clients',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Lucidly for multi-client website QA where humans triage on a Kanban and no agent owns the fix.',
                'Use ReviseMy when the studio runs coding agents and needs MCP handoff plus verification.',
                'Agencies can keep Lucidly for client marketing sites and ReviseMy for agent-built product work.',
                'If unlimited collaborators and agency pricing are the buying criteria and agents are irrelevant, Lucidly may be the better fit.',
            ],
            'verdict' => 'Choose ReviseMy if agents implement feedback and humans must verify on a board. Choose Lucidly if your core product is collaborative website QA with Kanban for human teams and clients.',
            'faq' => [
                [
                    'q' => 'Does ReviseMy have a Kanban like Lucidly?',
                    'a' => 'ReviseMy has an owner board with open → in progress → resolved → verified columns aimed at the agent loop — not a full agency project Kanban with assignees and digests.',
                ],
                [
                    'q' => 'Can clients comment without an account?',
                    'a' => 'Yes via guest links (suggestions). Owner marks stay authoritative. See the reviewers audience page for the human path.',
                ],
                [
                    'q' => 'Is ReviseMy open source?',
                    'a' => 'Yes — self-host or use a hosted deploy; homepage try tokens work without a ReviseMy account for reviewers.',
                ],
            ],
            'related' => ['pastel', 'marker-io', 'figma-comments'],
        ],

        'ai-design-critique' => [
            'slug' => 'ai-design-critique',
            'path' => '/alternatives/ai-design-critique',
            'label' => 'AI chat apps',
            'competitor' => 'AI chat apps',
            'competitor_links' => [
                ['label' => 'ChatGPT', 'url' => '/for/chatgpt'],
                ['label' => 'Claude', 'url' => '/for/claude'],
                ['label' => 'Copilot', 'url' => '/for/copilot'],
                ['label' => 'Cursor', 'url' => '/for/cursor'],
                ['label' => 'Grok', 'url' => '/for/grok'],
            ],
            'teaser' => 'Instant vision opinions vs human marks that decide the loop.',
            'icon' => 'sparkles',
            'title' => 'Best alternative to just using an AI chat app — ReviseMy',
            'description' => 'Looking past pasting screenshots into ChatGPT, Claude, Copilot, Cursor, or Grok for design feedback? ReviseMy keeps optional AI checklist and vision as second-opinion hints while human marks stay authoritative — with a board and MCP next_action for agents.',
            'keywords' => [
                'AI chat app alternative',
                'ChatGPT UI review alternative',
                'Claude vision design feedback',
                'human in the loop design review',
                'second opinion design hints',
            ],
            'headline' => 'Best alternative to just using an AI chat app',
            'subheadline' => 'Paste a screenshot into ChatGPT, Claude, Copilot, Cursor, or Grok and you get opinions. ReviseMy keeps AI as second opinion — humans mark, approve, and own the agent’s next_action.',
            'intro' => 'People look for an alternative to just using an AI chat app when the model sounds decisive, when agents treat a chat reply as a ship decision, or when feedback never sticks to regions across passes. Instant vision critique in chat is useful for brainstorming and taste prompts. ReviseMy is the stronger alternative when you need a durable loop: type-aware free checklist, optional BYOK vision regions as dashed hints, solid human marks as authority, a board for verification, and MCP tools so agents wait, apply, or stop for real.',
            'why_look' => [
                'Chat critiques vanish; agents re-invent the brief every pass.',
                'You need human must-fix / keep intent that overrides model confidence.',
                'Overlapping AI findings should enrich under a pin — not invent conflicting must-fixes.',
                'You want Refresh second opinion without flipping approve / request-changes.',
            ],
            'what_to_look_for' => [
                'Whether AI output is labeled as suggestions only',
                'Whether humans remain the only deciders',
                'Whether agents get structured next_action instead of prose',
                'Whether checklist runs without an API key and vision is optional BYOK',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/second-opinion',
                    'badge' => 'Recommended',
                    'summary' => 'Second opinion is built-in and deliberately non-authoritative. Your marks decide; the board and MCP close the loop.',
                    'best_for' => 'Anyone who likes AI hints but refuses to let them ship the product.',
                    'bullets' => [
                        'Free checklist on every upload',
                        'Optional Claude/OpenAI vision regions',
                        'Human marks = work_packets.pins',
                        'See /second-opinion for the full model',
                    ],
                ],
                [
                    'id' => 'figma-comments',
                    'label' => 'Figma comments',
                    'href' => '/alternatives/figma-comments',
                    'badge' => null,
                    'summary' => 'Human critique on design files — still the right surface before pixels exist in the product.',
                    'best_for' => 'Pre-build design critique without an agent loop.',
                    'bullets' => [
                        'Native to design files',
                        'Great for systems and craft',
                        'Not an MCP agent handoff',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep ChatGPT/Claude critique for quick taste brainstorms and learning prompts.',
                'Move to ReviseMy when you need persistence, authority, and an agent that follows next_action.',
                'You can paste a screenshot for a quick opinion, then open a ReviseMy review for the real pass.',
                'If you only ever want ephemeral chat advice and no ship gate, stick with an AI chat app.',
            ],
            'verdict' => 'Choose ReviseMy if AI should hint and humans should decide — with a board and MCP loop. Stick with an AI chat app if you only need disposable opinions and no structured agent handoff.',
            'faq' => [
                [
                    'q' => 'Does ReviseMy still use AI?',
                    'a' => 'Yes, optionally. A free checklist always runs; vision needs your own API key. Both are second opinion — never approve/request-changes.',
                ],
                [
                    'q' => 'Can the agent ignore second opinion?',
                    'a' => 'Agents should treat second_opinion as hints and prioritize work_packets.pins. That is the product contract.',
                ],
                [
                    'q' => 'Where do craft lenses come from?',
                    'a' => 'See the second opinion page — published craft sources distilled into hints, not celebrity endorsements of your UI.',
                ],
            ],
            'related' => ['figma-comments', 'marker-io', 'pastel'],
        ],

    ],

];
