<?php

return [

    'pages' => [

        'figma-comments' => [
            'slug' => 'figma-comments',
            'path' => '/alternatives/figma-comments',
            'label' => 'Figma comments',
            'competitor' => 'Figma comments',
            'competitor_link' => 'Figma',
            'competitor_url' => 'https://www.figma.com',
            'teaser' => 'Design-file critique vs agent-built UI that needs a ship loop.',
            'icon' => 'figma',
            'title' => 'Best Figma comments alternative for agent design checkups — ReviseMy',
            'description' => 'Looking for a Figma comments alternative when an AI agent ships the UI? ReviseMy gives humans authoritative marks on captures, a board, and structured next steps back over MCP — without replacing Figma for design files.',
            'keywords' => [
                'Figma comments alternative',
                'design review for AI agents',
                'visual feedback MCP',
                'human in the loop UI review',
                'agent design checkup',
            ],
            'headline' => 'Best Figma comments alternative when your agent ships the UI',
            'subheadline' => 'Figma comments are excellent on design files. ReviseMy is for the pixels your agent actually built — marks that drive next_action, not another thread in the canvas.',
            'intro' => 'People search for a Figma comments alternative for different reasons: the UI already exists in staging or screenshots, the builder is a coding agent that needs structured work packets, or design-file comments never map cleanly to “what to change next” in the repo. Figma remains the right place to critique components and systems in the design file. ReviseMy is the stronger alternative when the real problem is human-in-the-loop review of agent-built UI — with authoritative marks, a status board, and MCP handoff — without asking everyone to live in Figma for every pass.',
            'why_look' => [
                'The screen already shipped from an agent — feedback belongs on the capture, not only on a Figma frame that may be out of date.',
                'You need a clear next_action for the agent (wait, apply marks, open another pass), not a comment that dies in a design tool.',
                'Reviewers should mark and approve without a Figma seat; guests leave suggestions without owning the decision.',
                'You want open → resolved → verified status across passes, with optional before/after evidence — not only “resolved” in a comment thread.',
            ],
            'what_to_look_for' => [
                'Whether feedback lives on design files or on the pixels the agent shipped',
                'Whether the agent can poll structured work packets over MCP (or REST)',
                'Whether human marks stay authoritative vs optional AI hints',
                'Whether multi-pass reviews stay scannable on a board',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Human-in-the-loop design checkup for AI agents. Capture UI, websites, email, or slides; mark with intent; track the board; send next_action back over MCP.',
                    'best_for' => 'Teams where an agent builds UI and a human must approve before the loop stops.',
                    'bullets' => [
                        'Authoritative rose marks → work_packets.pins',
                        'Board: open → resolved → verified',
                        'Second opinion stays suggestions only',
                        'Free try token — no account for reviewers',
                    ],
                ],
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Fast visual annotation on live sites and assets via a share link — strong for client proofing without an agent in the loop.',
                    'best_for' => 'Agency or client website QA when nobody needs MCP next_action.',
                    'bullets' => [
                        'Link-based annotation',
                        'Live site and asset markup',
                        'Client-friendly, low install friction',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Figma comments for design-system and file-level critique before anything is built.',
                'Use ReviseMy after the agent ships screenshots or a URL — marks map to code work, not to layers.',
                'You can run both: Figma for craft in the file, ReviseMy for the agent ship loop.',
                'If there is no coding agent and all work stays in Figma, stay in Figma.',
            ],
            'verdict' => 'Choose ReviseMy if an agent ships UI and you need human marks that drive the next pass over MCP. Choose Figma comments if the artifact is still the design file and the builder is a human in Figma — not an agent waiting on next_action.',
            'faq' => [
                [
                    'q' => 'Is ReviseMy a Figma replacement?',
                    'a' => 'No. ReviseMy does not replace Figma as a design tool. It is an alternative feedback surface when the thing to review is agent-built UI (screenshots, capture URL, PDF, HTML) and the consumer of feedback is an agent.',
                ],
                [
                    'q' => 'Can designers use ReviseMy without MCP?',
                    'a' => 'Yes. Reviewers only need the secret review link. MCP setup is for the person connecting the agent.',
                ],
                [
                    'q' => 'What about Figma Make or Dev Mode handoff?',
                    'a' => 'Those stay in the Figma ecosystem. ReviseMy starts when pixels exist outside the file and an agent needs structured marks to continue.',
                ],
            ],
            'related' => ['pastel', 'lucidly', 'ai-design-critique'],
        ],

        'marker-io' => [
            'slug' => 'marker-io',
            'path' => '/alternatives/marker-io',
            'label' => 'Marker.io',
            'competitor' => 'Marker.io',
            'competitor_link' => 'Marker.io',
            'competitor_url' => 'https://marker.io',
            'teaser' => 'Website bug reports to PM tools vs an agent that owns the fix loop.',
            'icon' => 'marker-io',
            'title' => 'Best Marker.io alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Marker.io alternative when a coding agent should fix what you marked? ReviseMy turns human marks into MCP work packets and a verification board — without replacing Marker for classic website bug reporting into Jira or Linear.',
            'keywords' => [
                'Marker.io alternative',
                'website annotation alternative',
                'visual bug report MCP',
                'AI agent design feedback',
                'human in the loop QA',
            ],
            'headline' => 'Best Marker.io alternative when the fixer is an agent',
            'subheadline' => 'Marker.io shines at capturing live-site bugs with browser context into your PM stack. ReviseMy is for when the implementer is an AI agent that needs next_action — not another ticket queue.',
            'intro' => 'People look for a Marker.io alternative when tickets pile up, when the “developer” is a coding agent that never opens Jira, or when they want design intent (must-fix vs keep) and multi-pass verification — not only a screenshot-backed bug. Marker.io remains a strong fit for human QA teams filing into Linear, Jira, or Asana. ReviseMy is the stronger alternative when feedback must close the loop with an agent over MCP: mark on the capture, resolve with notes and after shots, verify on the board, approve or open the next pass.',
            'why_look' => [
                'The person fixing the UI is an agent that polls get_review — not a human watching a PM board.',
                'You need must-fix / nice to have / keep intent on the mark, not only a generic bug description.',
                'You want open → in progress → resolved → verified with before/after evidence across passes.',
                'Reviewers and guests should not need seats in a separate bug-reporting product.',
            ],
            'what_to_look_for' => [
                'Whether feedback feeds a PM tool or an agent MCP endpoint',
                'Whether “done” means ticket closed or human-verified on pixels',
                'Whether second-opinion AI hints stay non-authoritative',
                'Whether you review screenshots, URLs, email HTML, and slides — not only live sites',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Marks become work packets for your agent. The board tracks status until a human verifies. Optional vision hints never flip the decision.',
                    'best_for' => 'Agent-driven UI ship loops where humans still approve.',
                    'bullets' => [
                        'MCP create_review / get_review / resolve_marks',
                        'Owner board with verification gate',
                        'Guest links for non-authoritative suggestions',
                        'Webhook on review.decided for CI gates',
                    ],
                ],
                [
                    'id' => 'lucidly',
                    'label' => 'Lucidly',
                    'href' => '/alternatives/lucidly',
                    'badge' => null,
                    'summary' => 'Website QA with visual comments and a built-in Kanban — strong for agencies and clients without coding agents.',
                    'best_for' => 'Multi-client website proofing with task tracking in one place.',
                    'bullets' => [
                        'Comment on live/staging sites',
                        'Kanban from comments',
                        'Unlimited guests on the plan model',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Marker.io when human QA files bugs into Jira/Linear with browser metadata and nobody is running an agent loop.',
                'Use ReviseMy when the implementer is Cursor, Claude, Copilot, or similar and should follow next_action.',
                'A pragmatic split: Marker for classic production bug reports; ReviseMy for agent-built feature checkups.',
                'Do not force-fit Marker into an MCP agent workflow — the handoff shapes are different.',
            ],
            'verdict' => 'Choose ReviseMy if the fixer is an AI agent and you need marks, a verification board, and MCP next_action. Choose Marker.io if your workflow is human QA → ticket tracker and you do not need an agent design checkup loop.',
            'faq' => [
                [
                    'q' => 'Does ReviseMy replace Marker.io integrations?',
                    'a' => 'No. ReviseMy does not aim to be a Jira/Linear bug reporter. It hands structured work to agents. Keep Marker when PM-tool filing is the product.',
                ],
                [
                    'q' => 'Can ReviseMy capture a live URL?',
                    'a' => 'Yes — with capture_url and a public page_url (desktop + mobile). Localhost still needs screenshots or data URLs.',
                ],
                [
                    'q' => 'Who verifies fixes?',
                    'a' => 'Only humans verify on the board. Agents may resolve with notes and after images; they never flip verified.',
                ],
            ],
            'related' => ['pastel', 'simple-commenter', 'markup-io'],
        ],

        'pastel' => [
            'slug' => 'pastel',
            'path' => '/alternatives/pastel',
            'label' => 'Pastel',
            'competitor' => 'Pastel',
            'competitor_link' => 'Pastel',
            'competitor_url' => 'https://usepastel.com',
            'teaser' => 'Fast client annotation links vs agent checkups with next_action.',
            'icon' => 'pastel',
            'title' => 'Best Pastel alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Pastel alternative when coding agents ship the UI? ReviseMy keeps client-friendly review links while giving agents MCP work packets, a verification board, and type-aware checkups — without replacing Pastel for agency proofing without agents.',
            'keywords' => [
                'Pastel alternative',
                'usepastel alternative',
                'website annotation alternative',
                'design review for AI agents',
                'visual feedback MCP',
            ],
            'headline' => 'Best Pastel alternative when an agent is in the loop',
            'subheadline' => 'Pastel makes share-a-link annotation feel instant for clients. ReviseMy keeps that link simplicity for reviewers — and adds the MCP ship loop Pastel was never built to own.',
            'intro' => 'People search for a Pastel alternative when client comments need to become agent work, when reviews include app screenshots or email HTML — not only live sites — or when “inbox zero” comments still leave the coding agent guessing. Pastel is excellent for low-friction visual feedback and approvals on websites and assets. ReviseMy is the stronger alternative when a human must mark intent on captures and an agent must follow next_action until approve — with a board that separates resolved from verified.',
            'why_look' => [
                'Comments need to become structured pins for an agent, not only export to a PM tool.',
                'You review agent UI, slides, or email HTML as often as live marketing sites.',
                'You want authoritative owner marks vs guest suggestions vs optional AI hints.',
                'Multi-pass agent work needs before/after evidence and human verification.',
            ],
            'what_to_look_for' => [
                'Share-link friction for non-technical reviewers',
                'Whether an agent can consume the feedback without a human retyping tickets',
                'Coverage beyond live websites (screenshots, PDF, HTML)',
                'Clear separation of suggestions vs decisions',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Secret review links for humans; MCP for agents. Same checkup loop across UI, websites, email, and slides.',
                    'best_for' => 'Teams shipping with coding agents who still want client or designer eyes on the pixels.',
                    'bullets' => [
                        'No account required for reviewers',
                        'Guest links for suggestions only',
                        'Board + resolve_marks for the agent',
                        'Connectors for ChatGPT, Claude, Copilot, Cursor, Grok',
                    ],
                ],
                [
                    'id' => 'marker-io',
                    'label' => 'Marker.io',
                    'href' => '/alternatives/marker-io',
                    'badge' => null,
                    'summary' => 'Live-site visual bug reporting with rich browser context into existing PM tools.',
                    'best_for' => 'Human QA → Jira/Linear without an agent loop.',
                    'bullets' => [
                        'Browser and technical metadata',
                        'PM tool destinations',
                        'Production bug reporting workflows',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Pastel for agency client proofing when there is no coding agent and speed-to-annotate is the whole product.',
                'Use ReviseMy when the next reader of feedback is an agent on MCP.',
                'You can keep Pastel for marketing-site client rounds and ReviseMy for agent-built product UI.',
                'If export-to-Asana/Jira is the success metric and agents are out of scope, Pastel (or Marker/Lucidly) may fit better.',
            ],
            'verdict' => 'Choose ReviseMy if reviewers need a simple link and agents need structured next_action. Choose Pastel if the workflow is human client annotation on sites/assets with no agent ship loop.',
            'faq' => [
                [
                    'q' => 'Is ReviseMy as easy for clients as Pastel?',
                    'a' => 'Reviewers open a secret link and mark — no MCP, no ReviseMy account. Guest links are suggestions-only. Setup complexity sits with the person connecting the agent.',
                ],
                [
                    'q' => 'Does ReviseMy annotate live DOM elements like Pastel?',
                    'a' => 'ReviseMy marks regions on captured screenshots (including URL capture). It is capture-based, not a live DOM overlay product.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Pastel for classic client website rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['markup-io', 'workflow-design', 'marker-io'],
        ],

        'lucidly' => [
            'slug' => 'lucidly',
            'path' => '/alternatives/lucidly',
            'label' => 'Lucidly',
            'competitor' => 'Lucidly',
            'competitor_link' => 'Lucidly',
            'competitor_url' => 'https://lucidly.so',
            'teaser' => 'Agency website QA + Kanban vs agent MCP checkup loops.',
            'icon' => 'lucidly',
            'title' => 'Best Lucidly alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Lucidly alternative when coding agents ship the work? ReviseMy pairs human marks and a verification board with MCP next_action — without replacing Lucidly for agency website QA and client Kanban workflows.',
            'keywords' => [
                'Lucidly alternative',
                'lucidly.so alternative',
                'website QA alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best Lucidly alternative when agents ship the site',
            'subheadline' => 'Lucidly organizes website QA comments into a Kanban for agencies and clients. ReviseMy organizes marks for an agent that must fix, prove, and wait for human verify.',
            'intro' => 'People look for a Lucidly alternative when the “dev team” is increasingly an AI agent, when feedback spans app UI and email — not only marketing sites — or when status needs a human verification gate after the agent claims done. Lucidly is a strong, focused website QA and collaboration product (comments, guests, Kanban). ReviseMy is the stronger alternative when the consumer of feedback is an agent over MCP and “done” means a human verified the pixels on the board — not only a card moved on a Kanban.',
            'why_look' => [
                'Implementers are agents that need resolve_marks and next_action, not only assigned Kanban cards.',
                'You need before/after evidence and human-only verified status.',
                'Checkups include screenshots, PDF slides, or email HTML as well as live URLs.',
                'You want second-opinion checklist/vision hints that never override human marks.',
            ],
            'what_to_look_for' => [
                'Agency client QA vs agent-native ship loops',
                'Kanban for humans vs board lifecycle for agent+human',
                'Seat/guest model vs secret review links + try tokens',
                'Whether MCP connectors matter more than unlimited collaborators',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Open-source human-in-the-loop design review for agents. Marks, board, second opinion, connectors — built for the MCP checkup loop.',
                    'best_for' => 'Product and eng teams (and agencies) where agents build and humans approve.',
                    'bullets' => [
                        'MCP Apps or review_url workflows',
                        'Owner board with verify gate',
                        'Type-aware checkups (UI, website, email, slides)',
                        'Guest suggestions without giving away authority',
                    ],
                ],
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Lightweight link-based annotation — a close peer when you want speed over Kanban depth.',
                    'best_for' => 'Fast client markup without a heavy QA suite.',
                    'bullets' => [
                        'Share-link collaboration',
                        'Live site and asset feedback',
                        'Low onboarding for clients',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Lucidly for multi-client website QA where humans triage on a Kanban and no agent owns the fix.',
                'Use ReviseMy when the studio runs coding agents and needs MCP handoff plus verification.',
                'Agencies can keep Lucidly for client marketing sites and ReviseMy for agent-built product work.',
                'If unlimited collaborators and agency pricing are the buying criteria and agents are irrelevant, Lucidly may be the better fit.',
            ],
            'verdict' => 'Choose ReviseMy if agents implement feedback and humans must verify on a board. Choose Lucidly if your core product is collaborative website QA with Kanban for human teams and clients.',
            'faq' => [
                [
                    'q' => 'Does ReviseMy have a Kanban like Lucidly?',
                    'a' => 'ReviseMy has an owner board with open → in progress → resolved → verified columns aimed at the agent loop — not a full agency project Kanban with assignees and digests.',
                ],
                [
                    'q' => 'Can clients comment without an account?',
                    'a' => 'Yes via guest links (suggestions). Owner marks stay authoritative. See the reviewers audience page for the human path.',
                ],
                [
                    'q' => 'Is ReviseMy open source?',
                    'a' => 'Yes — self-host or use a hosted deploy; homepage try tokens work without a ReviseMy account for reviewers.',
                ],
            ],
            'related' => ['pastel', 'simple-commenter', 'workflow-design'],
        ],

        'markup-io' => [
            'slug' => 'markup-io',
            'path' => '/alternatives/markup-io',
            'label' => 'MarkUp.io',
            'competitor' => 'MarkUp.io',
            'competitor_link' => 'MarkUp.io',
            'competitor_url' => 'https://www.markup.io/',
            'teaser' => 'Annotate 30+ content types vs agent checkups with next_action.',
            'icon' => 'markup-io',
            'title' => 'Best MarkUp.io alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a MarkUp.io alternative when coding agents ship the UI? ReviseMy turns human marks on captures into MCP work packets and a verification board — without replacing MarkUp for broad creative review across websites, PDFs, images, and video.',
            'keywords' => [
                'MarkUp.io alternative',
                'Markup.io alternative',
                'website annotation alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best MarkUp.io alternative when an agent owns the fix',
            'subheadline' => 'MarkUp.io makes contextual feedback easy across websites, PDFs, images, and video. ReviseMy is for when that feedback must become next_action for a coding agent — with a board that separates resolved from verified.',
            'intro' => 'People search for a MarkUp.io alternative when creative review rounds need to become agent work, when the implementer never opens a comment inbox, or when “done” should mean a human verified the pixels — not only a thread closed on a markup. MarkUp.io remains excellent for broad, share-link annotation across many file types and agency-style review loops. ReviseMy is the stronger alternative when the consumer of feedback is an agent over MCP: mark intent on captures (screenshots, URL capture, PDF, HTML), follow work packets, prove fixes, and wait for human verify before the loop stops.',
            'why_look' => [
                'Comments need to become structured pins for an agent, not only a collaborative review canvas.',
                'You review agent-built UI, email HTML, or slides as often as marketing sites and decks.',
                'You want authoritative owner marks vs guest suggestions vs optional AI hints.',
                'Multi-pass agent work needs before/after evidence and a human-only verification gate.',
            ],
            'what_to_look_for' => [
                'Whether feedback feeds humans in a review tool or an agent MCP endpoint',
                'Coverage beyond live sites (screenshots, PDF, HTML) with type-aware checkups',
                'Whether “done” means comment resolved or human-verified on the board',
                'Share-link friction for non-technical reviewers without seats',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Secret review links for humans; MCP for agents. Same checkup loop across UI, websites, email, and slides.',
                    'best_for' => 'Teams where an agent builds and a human must approve before the loop stops.',
                    'bullets' => [
                        'Authoritative marks → work_packets.pins',
                        'Board: open → resolved → verified',
                        'Guest links for suggestions only',
                        'Connectors for ChatGPT, Claude, Copilot, Cursor, Grok',
                    ],
                ],
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Fast share-link annotation on live sites and assets — strong for client proofing without an agent loop.',
                    'best_for' => 'Agency website QA when nobody needs MCP next_action.',
                    'bullets' => [
                        'Link-based annotation',
                        'Live site and asset markup',
                        'Client-friendly, low install friction',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep MarkUp.io for creative teams annotating many content types when there is no coding agent in the ship loop.',
                'Use ReviseMy when the next reader of feedback is an agent on MCP.',
                'You can keep MarkUp for broad asset review rounds and ReviseMy for agent-built product UI.',
                'If unlimited collaborators and multi-format creative review are the product — and agents are out of scope — MarkUp may fit better.',
            ],
            'verdict' => 'Choose ReviseMy if reviewers need a simple link and agents need structured next_action. Choose MarkUp.io if the workflow is human visual review across many file types with no agent ship loop.',
            'faq' => [
                [
                    'q' => 'Is ReviseMy a MarkUp.io replacement?',
                    'a' => 'No. ReviseMy does not aim to be a general creative review canvas for 30+ file types. It is an alternative when feedback must drive an agent checkup loop with MCP next_action.',
                ],
                [
                    'q' => 'Does ReviseMy annotate live pages like MarkUp?',
                    'a' => 'ReviseMy marks regions on captured screenshots (including URL capture). It is capture-based, not a live multi-format markup product.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. MarkUp for classic creative review rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['pastel', 'workflow-design', 'marker-io'],
        ],

        'workflow-design' => [
            'slug' => 'workflow-design',
            'path' => '/alternatives/workflow-design',
            'label' => 'Workflow',
            'competitor' => 'Workflow',
            'competitor_link' => 'Workflow',
            'competitor_url' => 'https://www.workflow.design/',
            'teaser' => 'Designer client feedback + versions vs agent MCP ship loops.',
            'icon' => 'workflow-design',
            'title' => 'Best Workflow.design alternative for AI agent design checkups — ReviseMy',
            'description' => 'Looking for a Workflow.design alternative when coding agents ship the UI? ReviseMy keeps reviewer-friendly links while giving agents MCP work packets and a verification board — without replacing Workflow for designer-led client feedback and versioned creative revisions.',
            'keywords' => [
                'Workflow.design alternative',
                'Workflow design feedback alternative',
                'client design review alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best Workflow alternative when the fixer is an agent',
            'subheadline' => 'Workflow makes design feedback easy for clients — zero-signup links, versions, and clear revision rounds. ReviseMy is for when the implementer is a coding agent that needs next_action, not another creative inbox.',
            'intro' => 'People look for a Workflow alternative when client comments need to become agent work, when the “designer” shipping pixels is increasingly Cursor or Claude, or when status needs a human verification gate after the agent claims done. Workflow is excellent for designer–client review: share links, guided reviewers, version history, and feedback on designs, sites, PDFs, and more. ReviseMy is the stronger alternative when feedback must close the loop with an agent over MCP — mark intent on captures, resolve with notes and after shots, verify on the board, approve or open the next pass.',
            'why_look' => [
                'The person fixing the UI is an agent that polls get_review — not a designer ticking comments in a revision tool.',
                'You need must-fix / nice to have / keep intent that becomes work_packets.pins.',
                'You want open → resolved → verified with before/after evidence across agent passes.',
                'Checkups include app screenshots, email HTML, or slides — not only design files and marketing sites.',
            ],
            'what_to_look_for' => [
                'Creative revision inbox vs agent-native ship loop',
                'Whether AI is pre-flight hints or second-opinion only under human authority',
                'Zero-signup reviewer friction vs secret review + guest links',
                'Whether MCP connectors matter more than version history for humans',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Marks become work packets for your agent. The board tracks status until a human verifies. Optional vision hints never flip the decision.',
                    'best_for' => 'Agent-driven UI ship loops where humans still approve.',
                    'bullets' => [
                        'MCP create_review / get_review / resolve_marks',
                        'Owner board with verification gate',
                        'Guest links for non-authoritative suggestions',
                        'Type-aware checkups (UI, website, email, slides)',
                    ],
                ],
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Lightweight link-based annotation — a close peer when you want speed for client website markup.',
                    'best_for' => 'Fast client markup without a heavy creative suite.',
                    'bullets' => [
                        'Share-link collaboration',
                        'Live site and asset feedback',
                        'Low onboarding for clients',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Workflow for designer-led client feedback, versions, and creative approvals when no coding agent owns the fix.',
                'Use ReviseMy when the studio runs coding agents and needs MCP handoff plus verification.',
                'You can keep Workflow for design/client rounds and ReviseMy for agent-built product UI.',
                'If zero-signup creative review and version history are the buying criteria and agents are irrelevant, Workflow may fit better.',
            ],
            'verdict' => 'Choose ReviseMy if agents implement feedback and humans must verify on a board. Choose Workflow if your core product is designer–client visual feedback and versioned revisions without an agent ship loop.',
            'faq' => [
                [
                    'q' => 'Is ReviseMy as easy for clients as Workflow?',
                    'a' => 'Reviewers open a secret link and mark — no MCP, no ReviseMy account. Guest links are suggestions-only. Setup complexity sits with the person connecting the agent.',
                ],
                [
                    'q' => 'Does ReviseMy replace Workflow AI pre-flight?',
                    'a' => 'No. ReviseMy’s second opinion is optional checklist/vision hints under human authority. Workflow’s AI helps catch issues before client review — different job.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Workflow for classic design/client rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['pastel', 'markup-io', 'simple-commenter'],
        ],

        'simple-commenter' => [
            'slug' => 'simple-commenter',
            'path' => '/alternatives/simple-commenter',
            'label' => 'Simple Commenter',
            'competitor' => 'Simple Commenter',
            'competitor_link' => 'Simple Commenter',
            'competitor_url' => 'https://www.simplecommenter.com/',
            'teaser' => 'Live-site comment widget + MCP vs capture-based checkup loops.',
            'icon' => 'simple-commenter',
            'title' => 'Best Simple Commenter alternative for design checkup loops — ReviseMy',
            'description' => 'Looking for a Simple Commenter alternative when you need a human-in-the-loop design checkup? ReviseMy uses capture-based marks, a verification board, and MCP next_action — without replacing Simple Commenter for embedded live-site widgets and comment-to-ticket workflows.',
            'keywords' => [
                'Simple Commenter alternative',
                'website feedback widget alternative',
                'visual feedback MCP',
                'AI agent design review',
                'human in the loop QA',
            ],
            'headline' => 'Best Simple Commenter alternative for capture-based agent checkups',
            'subheadline' => 'Simple Commenter embeds a live-site feedback widget and can hand comments to agents over MCP. ReviseMy is a design checkup loop on captures — authoritative human marks, a verify gate, and next_action across UI, websites, email, and slides.',
            'intro' => 'People look for a Simple Commenter alternative when feedback must live on screenshots and multi-type captures — not only a scripted live page — when owner marks must stay authoritative over guests and AI hints, or when “done” means human-verified pixels after an agent pass. Simple Commenter is strong for agencies and teams that want an on-page widget, PM integrations, and an MCP path that pulls open comments for coding agents. ReviseMy is the stronger alternative when you want a dedicated checkup surface: create_review from images, URL capture, PDF, or HTML; human pins as work_packets; board lifecycle with verify; second opinion that never decides; and next_action that tells the agent to wait, apply, or stop.',
            'why_look' => [
                'You need review on captures and artifact types beyond an embedded live-site widget.',
                'Owner marks, guest suggestions, and AI hints must stay clearly separated.',
                '“Done” should mean human-verified on the board — not only a comment marked resolved by an agent.',
                'You want type-aware checkups (UI, website, email, slides) with the same MCP ship loop.',
            ],
            'what_to_look_for' => [
                'Live DOM widget vs capture-based review surface',
                'Comment→ticket/PM routing vs design checkup next_action semantics',
                'Whether agents can mark comments done vs wait for human verify',
                'Whether second-opinion AI stays non-authoritative',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/#setup',
                    'badge' => 'Recommended',
                    'summary' => 'Human-in-the-loop design checkup for AI agents. Capture, mark with intent, verify on the board, send next_action back over MCP.',
                    'best_for' => 'Teams that want a review loop with authority and verification — not only a live-site comment inbox.',
                    'bullets' => [
                        'Capture-based marks → work_packets.pins',
                        'Board: open → resolved → verified (human-only verify)',
                        'Second opinion stays suggestions only',
                        'Free try token — no account for reviewers',
                    ],
                ],
                [
                    'id' => 'marker-io',
                    'label' => 'Marker.io',
                    'href' => '/alternatives/marker-io',
                    'badge' => null,
                    'summary' => 'Live-site visual bug reporting with rich browser context into existing PM tools.',
                    'best_for' => 'Human QA → Jira/Linear without a design checkup board.',
                    'bullets' => [
                        'Browser and technical metadata',
                        'PM tool destinations',
                        'Production bug reporting workflows',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Simple Commenter when you want an embedded live-site widget, Slack/Jira routing, and agents that pull open comments to fix and mark done.',
                'Use ReviseMy when you need a capture-based checkup with owner authority, guest vs hint separation, and human-only verify.',
                'A pragmatic split: Simple Commenter for ongoing on-page client feedback; ReviseMy for agent-built feature passes and multi-artifact checkups.',
                'ReviseMy is not “the only MCP visual feedback tool” — Simple Commenter’s MCP is real; the products optimize for different loops.',
            ],
            'verdict' => 'Choose ReviseMy if you need capture-based design checkups with authoritative marks, a verification board, and next_action. Choose Simple Commenter if your core product is a live-site feedback widget (with optional agent MCP) into the tools your team already uses.',
            'faq' => [
                [
                    'q' => 'Doesn’t Simple Commenter already have MCP?',
                    'a' => 'Yes — agents can list comments, fix code, and update status. ReviseMy’s MCP is shaped around a design checkup loop: create_review, work_packets.pins, next_action, and a human verify gate. Different contract, overlapping audience.',
                ],
                [
                    'q' => 'Is ReviseMy a live-site widget?',
                    'a' => 'No. Reviewers open a secret review link (or MCP Apps inline UI) and mark captures. There is no embed script for production pages.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Simple Commenter for embedded client feedback on live sites; ReviseMy for structured agent checkups on captures across UI, email, and slides.',
                ],
            ],
            'related' => ['marker-io', 'workflow-design', 'pastel'],
        ],

        'ai-design-critique' => [
            'slug' => 'ai-design-critique',
            'path' => '/alternatives/ai-design-critique',
            'label' => 'AI chat apps',
            'competitor' => 'AI chat apps',
            'competitor_links' => [
                ['label' => 'ChatGPT', 'url' => '/for/chatgpt'],
                ['label' => 'Claude', 'url' => '/for/claude'],
                ['label' => 'Copilot', 'url' => '/for/copilot'],
                ['label' => 'Cursor', 'url' => '/for/cursor'],
                ['label' => 'Grok', 'url' => '/for/grok'],
            ],
            'teaser' => 'Instant vision opinions vs human marks that decide the loop.',
            'icon' => 'sparkles',
            'title' => 'Best alternative to just using an AI chat app — ReviseMy',
            'description' => 'Looking past pasting screenshots into ChatGPT, Claude, Copilot, Cursor, or Grok for design feedback? ReviseMy keeps optional AI checklist and vision as second-opinion hints while human marks stay authoritative — with a board and MCP next_action for agents.',
            'keywords' => [
                'AI chat app alternative',
                'ChatGPT UI review alternative',
                'Claude vision design feedback',
                'human in the loop design review',
                'second opinion design hints',
            ],
            'headline' => 'Best alternative to just using an AI chat app',
            'subheadline' => 'Paste a screenshot into ChatGPT, Claude, Copilot, Cursor, or Grok and you get opinions. ReviseMy keeps AI as second opinion — humans mark, approve, and own the agent’s next_action.',
            'intro' => 'People look for an alternative to just using an AI chat app when the model sounds decisive, when agents treat a chat reply as a ship decision, or when feedback never sticks to regions across passes. Instant vision critique in chat is useful for brainstorming and taste prompts. ReviseMy is the stronger alternative when you need a durable loop: type-aware free checklist, optional BYOK vision regions as dashed hints, solid human marks as authority, a board for verification, and MCP tools so agents wait, apply, or stop for real.',
            'why_look' => [
                'Chat critiques vanish; agents re-invent the brief every pass.',
                'You need human must-fix / keep intent that overrides model confidence.',
                'Overlapping AI findings should enrich under a pin — not invent conflicting must-fixes.',
                'You want Refresh second opinion without flipping approve / request-changes.',
            ],
            'what_to_look_for' => [
                'Whether AI output is labeled as suggestions only',
                'Whether humans remain the only deciders',
                'Whether agents get structured next_action instead of prose',
                'Whether checklist runs without an API key and vision is optional BYOK',
            ],
            'recommended' => [
                [
                    'id' => 'revisemy',
                    'label' => 'ReviseMy',
                    'href' => '/second-opinion',
                    'badge' => 'Recommended',
                    'summary' => 'Second opinion is built-in and deliberately non-authoritative. Your marks decide; the board and MCP close the loop.',
                    'best_for' => 'Anyone who likes AI hints but refuses to let them ship the product.',
                    'bullets' => [
                        'Free checklist on every upload',
                        'Optional Claude/OpenAI vision regions',
                        'Human marks = work_packets.pins',
                        'See /second-opinion for the full model',
                    ],
                ],
                [
                    'id' => 'figma-comments',
                    'label' => 'Figma comments',
                    'href' => '/alternatives/figma-comments',
                    'badge' => null,
                    'summary' => 'Human critique on design files — still the right surface before pixels exist in the product.',
                    'best_for' => 'Pre-build design critique without an agent loop.',
                    'bullets' => [
                        'Native to design files',
                        'Great for systems and craft',
                        'Not an MCP agent handoff',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep ChatGPT/Claude critique for quick taste brainstorms and learning prompts.',
                'Move to ReviseMy when you need persistence, authority, and an agent that follows next_action.',
                'You can paste a screenshot for a quick opinion, then open a ReviseMy review for the real pass.',
                'If you only ever want ephemeral chat advice and no ship gate, stick with an AI chat app.',
            ],
            'verdict' => 'Choose ReviseMy if AI should hint and humans should decide — with a board and MCP loop. Stick with an AI chat app if you only need disposable opinions and no structured agent handoff.',
            'faq' => [
                [
                    'q' => 'Does ReviseMy still use AI?',
                    'a' => 'Yes, optionally. A free checklist always runs; vision needs your own API key. Both are second opinion — never approve/request-changes.',
                ],
                [
                    'q' => 'Can the agent ignore second opinion?',
                    'a' => 'Agents should treat second_opinion as hints and prioritize work_packets.pins. That is the product contract.',
                ],
                [
                    'q' => 'Where do craft lenses come from?',
                    'a' => 'See the second opinion page — published craft sources distilled into hints, not celebrity endorsements of your UI.',
                ],
            ],
            'related' => ['figma-comments', 'marker-io', 'pastel'],
        ],

    ],

];
