<?php

return [

    /*
    | ReviseMy's own entry, shown first in every comparison's recommendations.
    */
    'revisemy' => [
        'label' => 'ReviseMy',
        'href' => '/connect',
        'badge' => 'This one',
        'summary' => 'Visual feedback for your agent. It captures UI, a page, an email or slides; you mark what matters and decide; it reads your marks and keeps going.',
        'best_for' => 'Teams where an agent builds the work and a person approves it before the loop stops.',
        'bullets' => [
            'Your marks are the brief the agent works from',
            'Every mark from open to resolved to verified',
            'Second opinion stays a suggestion',
            'No account — reviewers only need the link',
        ],
    ],

    'pages' => [

        'figma-comments' => [
            'slug' => 'figma-comments',
            'path' => '/alternatives/figma-comments',
            'label' => 'Figma comments',
            'competitor' => 'Figma comments',
            'competitor_link' => 'Figma',
            'competitor_url' => 'https://www.figma.com',
            'teaser' => 'Design-file critique vs agent-built UI that needs a ship loop.',
            'icon' => 'figma',
            'title' => 'Best Figma comments alternative for agent design checkups — ReviseMy',
            'description' => 'A Figma comments alternative for when your AI agent ships the UI: marks on the real captures, a board, and next steps over MCP. Keep Figma for files.',
            'keywords' => [
                'Figma comments alternative',
                'design review for AI agents',
                'visual feedback MCP',
                'human in the loop UI review',
                'agent design checkup',
            ],
            'headline' => 'Best Figma comments alternative when your agent ships the UI',
            'subheadline' => 'Figma comments are excellent on design files. ReviseMy is for the pixels your agent actually built — marks that drive next_action, not another thread in the canvas.',
            'compare' => [
                'ending' => 'thread',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'them_end' => 'Figma’s MCP server doesn’t read comments, so someone retypes this for the agent.',
                'us_end' => 'The agent reads the mark itself, and only you can mark the fix verified.',
            ],
            'why_look' => [
                'The screen already shipped from an agent — feedback belongs on the capture, not only on a Figma frame that may be out of date.',
                'You need a clear next_action for the agent (wait, apply marks, open another pass), not a comment that dies in a design tool.',
                'Reviewers should mark and approve without a Figma seat; guests leave suggestions without owning the decision.',
                'You want open → resolved → verified status across passes, with optional before/after evidence — not only “resolved” in a comment thread.',
            ],
            'what_to_look_for' => [
                'Whether feedback lives on design files or on the pixels the agent shipped',
                'Whether the agent can poll structured work packets over MCP (or REST)',
                'Whether human marks stay authoritative vs optional AI hints',
                'Whether multi-pass reviews stay scannable on a board',
            ],
            'recommended' => [
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Share-link annotation on live sites, images, PDFs and video, with an MCP server that lets agents read, reply to and resolve comments.',
                    'best_for' => 'Client proofing across many formats, where a resolved comment is enough of a finish line.',
                    'bullets' => [
                        'Link-based annotation',
                        'Live site and asset markup',
                        'Client-friendly, low install friction',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Figma comments for design-system and file-level critique before anything is built.',
                'Use ReviseMy after the agent ships screenshots or a URL — marks map to code work, not to layers.',
                'You can run both: Figma for craft in the file, ReviseMy for the agent ship loop.',
                'If there is no coding agent and all work stays in Figma, stay in Figma.',
            ],
            'faq' => [
                [
                    'q' => 'Is ReviseMy a Figma replacement?',
                    'a' => 'No. ReviseMy does not replace Figma as a design tool. It is an alternative feedback surface when the thing to review is agent-built UI (screenshots, capture URL, PDF, HTML) and the consumer of feedback is an agent.',
                ],
                [
                    'q' => 'Can designers use ReviseMy without MCP?',
                    'a' => 'Yes. Reviewers only need the secret review link. MCP setup is for the person connecting the agent.',
                ],
                [
                    'q' => 'What about Figma Make or Dev Mode handoff?',
                    'a' => 'Those stay in the Figma ecosystem. ReviseMy starts when pixels exist outside the file and an agent needs structured marks to continue.',
                ],
            ],
            'related' => ['pastel', 'lucidly', 'ai-design-critique'],
        ],

        'marker-io' => [
            'slug' => 'marker-io',
            'path' => '/alternatives/marker-io',
            'label' => 'Marker.io',
            'competitor' => 'Marker.io',
            'competitor_link' => 'Marker.io',
            'competitor_url' => 'https://marker.io',
            'teaser' => 'Website bug reports to PM tools vs an agent that owns the fix loop.',
            'icon' => 'marker-io',
            'title' => 'Best Marker.io alternative for AI agent design checkups — ReviseMy',
            'description' => 'A Marker.io alternative for when a coding agent fixes what you mark: marks become MCP work, with a board to verify. Keep Marker for Jira bug reports.',
            'keywords' => [
                'Marker.io alternative',
                'website annotation alternative',
                'visual bug report MCP',
                'AI agent design feedback',
                'human in the loop QA',
            ],
            'headline' => 'Best Marker.io alternative when the fixer is an agent',
            'subheadline' => 'Marker.io shines at capturing live-site bugs with browser context into your PM stack. ReviseMy is for when the implementer is an AI agent that needs next_action — not another ticket queue.',
            'compare' => [
                'ending' => 'ticket',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'them_end' => 'The agent can close the issue over MCP. Nothing asks the reporter to confirm the fix.',
                'us_end' => 'The agent resolves with an after shot. Only you can mark it verified.',
            ],
            'why_look' => [
                'The person fixing the UI is an agent that polls get_review — not a human watching a PM board.',
                'You need must-fix / nice to have / keep intent on the mark, not only a generic bug description.',
                'You want open → in progress → resolved → verified with before/after evidence across passes.',
                'The agent should open the review from its own capture, not wait for someone to file a bug.',
            ],
            'what_to_look_for' => [
                'Whether feedback feeds a PM tool or an agent MCP endpoint',
                'Whether “done” means ticket closed or human-verified on pixels',
                'Whether second-opinion AI hints stay non-authoritative',
                'Whether you review screenshots, URLs, email HTML, and slides — not only live sites',
            ],
            'recommended' => [
                [
                    'id' => 'lucidly',
                    'label' => 'Lucidly',
                    'href' => '/alternatives/lucidly',
                    'badge' => null,
                    'summary' => 'Live-site QA with per-device comments and a built-in Kanban. Agents can read comments and move cards over MCP.',
                    'best_for' => 'Multi-client website proofing with task tracking in one place.',
                    'bullets' => [
                        'Comment on live/staging sites',
                        'Kanban from comments',
                        'Unlimited guests on the plan model',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Marker.io when bugs need console logs, session replay and a two-way sync with Jira or Linear.',
                'Use ReviseMy when the implementer is Cursor, Claude, Copilot, or similar and should follow next_action.',
                'A pragmatic split: Marker for classic production bug reports; ReviseMy for agent-built feature checkups.',
                'Marker’s MCP lets agents read and resolve issues. ReviseMy adds intent on each mark, before/after evidence, and a verify step only you can take.',
            ],
            'faq' => [
                [
                    'q' => 'Does ReviseMy replace Marker.io integrations?',
                    'a' => 'No. ReviseMy does not aim to be a Jira/Linear bug reporter. It hands structured work to agents. Keep Marker when PM-tool filing is the product.',
                ],
                [
                    'q' => 'Can ReviseMy capture a live URL?',
                    'a' => 'Yes — with capture_url and a public page_url (desktop, mobile and tablet). Localhost still needs screenshots or data URLs.',
                ],
                [
                    'q' => 'Who verifies fixes?',
                    'a' => 'Only humans verify on the board. Agents may resolve with notes and after images; they never flip verified.',
                ],
            ],
            'related' => ['pastel', 'simple-commenter', 'markup-io'],
        ],

        'pastel' => [
            'slug' => 'pastel',
            'path' => '/alternatives/pastel',
            'label' => 'Pastel',
            'competitor' => 'Pastel',
            'competitor_link' => 'Pastel',
            'competitor_url' => 'https://usepastel.com',
            'teaser' => 'Fast client annotation links vs agent checkups with next_action.',
            'icon' => 'pastel',
            'title' => 'Best Pastel alternative for AI agent design checkups — ReviseMy',
            'description' => 'A Pastel alternative for when coding agents ship the UI: client-friendly review links, MCP work and a board to verify. Keep Pastel for multi-format client proofing.',
            'keywords' => [
                'Pastel alternative',
                'usepastel alternative',
                'website annotation alternative',
                'design review for AI agents',
                'visual feedback MCP',
            ],
            'headline' => 'Best Pastel alternative when an agent is in the loop',
            'subheadline' => 'Pastel makes share-a-link annotation feel instant for clients. Its MCP server lets agents resolve comments. ReviseMy adds what comes after: intent on every mark, before/after evidence, and a verified state only you can set.',
            'compare' => [
                'ending' => 'thread',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'agent' => true,
                'them_end' => 'The agent replies and resolves. To check, you reopen the site and look for yourself.',
                'us_end' => 'Must fix, nit or keep tells the agent what matters. Only you mark it verified.',
            ],
            'why_look' => [
                'Comments need intent (must fix, nit, keep this) so the agent knows what matters, not just free text.',
                'You review agent UI, slides, or email HTML as often as live marketing sites.',
                'You want authoritative owner marks vs guest suggestions vs optional AI hints.',
                'Multi-pass agent work needs before/after evidence and human verification.',
            ],
            'what_to_look_for' => [
                'Share-link friction for non-technical reviewers',
                'Whether an agent can consume the feedback without a human retyping tickets',
                'Coverage beyond live websites (screenshots, PDF, HTML)',
                'Clear separation of suggestions vs decisions',
            ],
            'recommended' => [
                [
                    'id' => 'marker-io',
                    'label' => 'Marker.io',
                    'href' => '/alternatives/marker-io',
                    'badge' => null,
                    'summary' => 'Live-site visual bug reporting with rich browser context into existing PM tools.',
                    'best_for' => 'Bug reports that need console logs, session replay and Jira/Linear sync.',
                    'bullets' => [
                        'Browser and technical metadata',
                        'PM tool destinations',
                        'Production bug reporting workflows',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Pastel for client proofing across video, images and PDFs, or when a resolved comment is all the sign-off you need.',
                'Use ReviseMy when the agent should open the review itself and you want to verify each fix against a before/after.',
                'You can keep Pastel for marketing-site client rounds and ReviseMy for agent-built product UI.',
                'If export to Asana or Jira is the success metric, Pastel (or Marker.io or Lucidly) may fit better.',
            ],
            'faq' => [
                [
                    'q' => 'Is ReviseMy as easy for clients as Pastel?',
                    'a' => 'Reviewers open a secret link and mark — no MCP, no ReviseMy account. Guest links are suggestions-only. Setup complexity sits with the person connecting the agent.',
                ],
                [
                    'q' => 'Does ReviseMy annotate live DOM elements like Pastel?',
                    'a' => 'ReviseMy marks regions on captured screenshots (including URL capture). It is capture-based, not a live DOM overlay product.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Pastel for classic client website rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['markup-io', 'workflow-design', 'marker-io'],
        ],

        'lucidly' => [
            'slug' => 'lucidly',
            'path' => '/alternatives/lucidly',
            'label' => 'Lucidly',
            'competitor' => 'Lucidly',
            'competitor_link' => 'Lucidly',
            'competitor_url' => 'https://lucidly.so',
            'teaser' => 'Kanban website QA vs agent fixes you verify against a before and after.',
            'icon' => 'lucidly',
            'title' => 'Best Lucidly alternative for AI agent design checkups — ReviseMy',
            'description' => 'A Lucidly alternative for when coding agents ship the work: your marks, a board to verify, and next_action over MCP. Keep Lucidly for agency site QA.',
            'keywords' => [
                'Lucidly alternative',
                'lucidly.so alternative',
                'website QA alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best Lucidly alternative when agents ship the site',
            'subheadline' => 'Lucidly organizes website QA comments into a Kanban for agencies and clients. ReviseMy organizes marks for an agent that must fix, prove, and wait for human verify.',
            'compare' => [
                'ending' => 'kanban',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'them_end' => 'The agent moves the card to Resolved. To check, you reopen the live site.',
                'us_end' => 'The fix comes back with before and after, and only you mark it verified.',
            ],
            'why_look' => [
                'Your agent should open the review itself from its own capture, not wait for someone to set up a project.',
                'You need before/after evidence and human-only verified status.',
                'Checkups include screenshots, PDF slides, or email HTML as well as live URLs.',
                'You want second-opinion checklist/vision hints that never override human marks.',
            ],
            'what_to_look_for' => [
                'Agency client QA vs agent-native ship loops',
                'Kanban for humans vs board lifecycle for agent+human',
                'Seat/guest model vs secret review links + try tokens',
                'Whether “resolved” is the finish line, or you verify each fix',
            ],
            'recommended' => [
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Lightweight link-based annotation — a close peer when you want speed over Kanban depth.',
                    'best_for' => 'Fast client markup without a heavy QA suite.',
                    'bullets' => [
                        'Share-link collaboration',
                        'Live site and asset feedback',
                        'Low onboarding for clients',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Lucidly for multi-page live-site QA with real-time collaboration and per-device comments.',
                'Use ReviseMy when each agent fix should come back with before/after evidence and wait for you to verify it.',
                'Agencies can keep Lucidly for client marketing sites and ReviseMy for agent-built product work.',
                'If unlimited collaborators and a low flat price are the buying criteria, Lucidly may be the better fit.',
            ],
            'faq' => [
                [
                    'q' => 'Does ReviseMy have a Kanban like Lucidly?',
                    'a' => 'ReviseMy has an owner board with open → in progress → resolved → verified columns aimed at the agent loop — not a full agency project Kanban with assignees and digests.',
                ],
                [
                    'q' => 'Can clients comment without an account?',
                    'a' => 'Yes via guest links (suggestions). Owner marks stay authoritative. See the reviewers audience page for the human path.',
                ],
                [
                    'q' => 'Is ReviseMy open source?',
                    'a' => 'Yes — self-host or use a hosted deploy; homepage try tokens work without a ReviseMy account for reviewers.',
                ],
            ],
            'related' => ['pastel', 'simple-commenter', 'workflow-design'],
        ],

        'markup-io' => [
            'slug' => 'markup-io',
            'path' => '/alternatives/markup-io',
            'label' => 'MarkUp.io',
            'competitor' => 'MarkUp.io',
            'competitor_link' => 'MarkUp.io',
            'competitor_url' => 'https://www.markup.io/',
            'teaser' => 'Annotate 30+ content types vs agent checkups with next_action.',
            'icon' => 'markup-io',
            'title' => 'Best MarkUp.io alternative for AI agent design checkups — ReviseMy',
            'description' => 'A MarkUp.io alternative for when coding agents ship the UI: marks on captures become MCP work, with a board to verify. Keep MarkUp for creative review.',
            'keywords' => [
                'MarkUp.io alternative',
                'Markup.io alternative',
                'website annotation alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best MarkUp.io alternative when an agent owns the fix',
            'subheadline' => 'MarkUp.io makes contextual feedback easy across websites, PDFs, images, and video. ReviseMy is for when that feedback must become next_action for a coding agent — with a board that separates resolved from verified.',
            'compare' => [
                'ending' => 'thread',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'priority' => 'High',
                'reply' => 'I’ll add it to the dev ticket.',
                'them_end' => 'There’s no agent connection, so the pin gets copied into a ticket or prompt.',
                'us_end' => 'The mark is the agent’s brief, and the fix comes back for you to verify.',
            ],
            'why_look' => [
                'Comments need to become structured work for an agent, not only a collaborative review canvas.',
                'You review agent-built UI, email HTML, or slides as often as marketing sites and decks.',
                'You want authoritative owner marks vs guest suggestions vs optional AI hints.',
                'Multi-pass agent work needs before/after evidence and a human-only verification gate.',
            ],
            'what_to_look_for' => [
                'Whether feedback feeds humans in a review tool or an agent MCP endpoint',
                'Coverage beyond live sites (screenshots, PDF, HTML) with type-aware checkups',
                'Whether “done” means comment resolved or human-verified on the board',
                'Share-link friction for non-technical reviewers without seats',
            ],
            'recommended' => [
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Share-link annotation on live sites, images, PDFs and video, with an MCP server that lets agents read, reply to and resolve comments.',
                    'best_for' => 'Client proofing across many formats, where a resolved comment is enough of a finish line.',
                    'bullets' => [
                        'Link-based annotation',
                        'Live site and asset markup',
                        'Client-friendly, low install friction',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep MarkUp.io for creative teams annotating many content types when there is no coding agent in the ship loop.',
                'Use ReviseMy when the next reader of feedback is an agent on MCP.',
                'You can keep MarkUp for broad asset review rounds and ReviseMy for agent-built product UI.',
                'If unlimited collaborators and multi-format creative review are the product — and agents are out of scope — MarkUp may fit better.',
            ],
            'faq' => [
                [
                    'q' => 'Is ReviseMy a MarkUp.io replacement?',
                    'a' => 'No. ReviseMy does not aim to be a general creative review canvas for 30+ file types. It is an alternative when feedback must drive an agent checkup loop with MCP next_action.',
                ],
                [
                    'q' => 'Does ReviseMy annotate live pages like MarkUp?',
                    'a' => 'ReviseMy marks regions on captured screenshots (including URL capture). It is capture-based, not a live multi-format markup product.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. MarkUp for classic creative review rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['pastel', 'workflow-design', 'marker-io'],
        ],

        'workflow-design' => [
            'slug' => 'workflow-design',
            'path' => '/alternatives/workflow-design',
            'label' => 'Workflow',
            'competitor' => 'Workflow',
            'competitor_link' => 'Workflow',
            'competitor_url' => 'https://www.workflow.design/',
            'teaser' => 'Designer client feedback + versions vs agent MCP ship loops.',
            'icon' => 'workflow-design',
            'title' => 'Best Workflow.design alternative for AI agent design checkups — ReviseMy',
            'description' => 'A Workflow.design alternative for when coding agents ship the UI: reviewer-friendly links, MCP work and a board. Keep Workflow for designer-led rounds.',
            'keywords' => [
                'Workflow.design alternative',
                'Workflow design feedback alternative',
                'client design review alternative',
                'visual feedback for AI agents',
                'design checkup MCP',
            ],
            'headline' => 'Best Workflow alternative when the fixer is an agent',
            'subheadline' => 'Workflow makes design feedback easy for clients — zero-signup links, versions, and clear revision rounds. ReviseMy is for when the implementer is a coding agent that needs next_action, not another creative inbox.',
            'compare' => [
                'ending' => 'versions',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'them_end' => 'A person reworks v4 by hand. No agent reads the comments.',
                'us_end' => 'The agent opens pass 2 from your marks. You verify and approve.',
            ],
            'why_look' => [
                'The person fixing the UI is an agent that polls get_review — not a designer ticking comments in a revision tool.',
                'You need must-fix / nice to have / keep intent that becomes work_packets.pins.',
                'You want open → resolved → verified with before/after evidence across agent passes.',
                'Checkups include app screenshots, email HTML, or slides — not only design files and marketing sites.',
            ],
            'what_to_look_for' => [
                'Creative revision inbox vs agent-native ship loop',
                'Whether AI is pre-flight hints or second-opinion only under human authority',
                'Zero-signup reviewer friction vs secret review + guest links',
                'Whether MCP connectors matter more than version history for humans',
            ],
            'recommended' => [
                [
                    'id' => 'pastel',
                    'label' => 'Pastel',
                    'href' => '/alternatives/pastel',
                    'badge' => null,
                    'summary' => 'Lightweight link-based annotation — a close peer when you want speed for client website markup.',
                    'best_for' => 'Fast client markup without a heavy creative suite.',
                    'bullets' => [
                        'Share-link collaboration',
                        'Live site and asset feedback',
                        'Low onboarding for clients',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Workflow for designer-led client feedback, versions, and creative approvals when no coding agent owns the fix.',
                'Use ReviseMy when the studio runs coding agents and needs MCP handoff plus verification.',
                'You can keep Workflow for design/client rounds and ReviseMy for agent-built product UI.',
                'If zero-signup creative review and version history are the buying criteria and agents are irrelevant, Workflow may fit better.',
            ],
            'faq' => [
                [
                    'q' => 'Is ReviseMy as easy for clients as Workflow?',
                    'a' => 'Reviewers open a secret link and mark — no MCP, no ReviseMy account. Guest links are suggestions-only. Setup complexity sits with the person connecting the agent.',
                ],
                [
                    'q' => 'Does ReviseMy replace Workflow AI pre-flight?',
                    'a' => 'No. ReviseMy’s second opinion is optional checklist/vision hints under human authority. Workflow’s AI helps catch issues before client review — different job.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Workflow for classic design/client rounds; ReviseMy when an agent owns the implementation pass.',
                ],
            ],
            'related' => ['pastel', 'markup-io', 'simple-commenter'],
        ],

        'simple-commenter' => [
            'slug' => 'simple-commenter',
            'path' => '/alternatives/simple-commenter',
            'label' => 'Simple Commenter',
            'competitor' => 'Simple Commenter',
            'competitor_link' => 'Simple Commenter',
            'competitor_url' => 'https://www.simplecommenter.com/',
            'teaser' => 'Live-site comment widget + MCP vs capture-based checkup loops.',
            'icon' => 'simple-commenter',
            'title' => 'Best Simple Commenter alternative for design checkup loops — ReviseMy',
            'description' => 'A Simple Commenter alternative for a human-in-the-loop checkup: marks on captures, a board and next_action over MCP. Keep it for live-site comment widgets.',
            'keywords' => [
                'Simple Commenter alternative',
                'website feedback widget alternative',
                'visual feedback MCP',
                'AI agent design review',
                'human in the loop QA',
            ],
            'headline' => 'Best Simple Commenter alternative for capture-based agent checkups',
            'subheadline' => 'Simple Commenter embeds a live-site feedback widget and can hand comments to agents over MCP. ReviseMy is a design checkup loop on captures — authoritative human marks, a verify gate, and next_action across UI, websites, email, and slides.',
            'compare' => [
                'ending' => 'widget',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'them_end' => 'The agent can set it to Done. The client isn’t asked to confirm the fix.',
                'us_end' => 'The agent resolves with an after shot. Only you can mark it verified.',
            ],
            'why_look' => [
                'You need review on captures and artifact types beyond an embedded live-site widget.',
                'Owner marks, guest suggestions, and AI hints must stay clearly separated.',
                '“Done” should mean human-verified on the board — not only a comment marked resolved by an agent.',
                'You want type-aware checkups (UI, website, email, slides) with the same MCP ship loop.',
            ],
            'what_to_look_for' => [
                'Live DOM widget vs capture-based review surface',
                'Comment→ticket/PM routing vs design checkup next_action semantics',
                'Whether agents can mark comments done vs wait for human verify',
                'Whether second-opinion AI stays non-authoritative',
            ],
            'recommended' => [
                [
                    'id' => 'marker-io',
                    'label' => 'Marker.io',
                    'href' => '/alternatives/marker-io',
                    'badge' => null,
                    'summary' => 'Live-site visual bug reporting with rich browser context into existing PM tools.',
                    'best_for' => 'Human QA → Jira/Linear without a design checkup board.',
                    'bullets' => [
                        'Browser and technical metadata',
                        'PM tool destinations',
                        'Production bug reporting workflows',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep Simple Commenter when you want an embedded live-site widget, Slack/Jira routing, and agents that pull open comments to fix and mark done.',
                'Use ReviseMy when you need a capture-based checkup with owner authority, guest vs hint separation, and human-only verify.',
                'A pragmatic split: Simple Commenter for ongoing on-page client feedback; ReviseMy for agent-built feature passes and multi-artifact checkups.',
                'ReviseMy is not “the only MCP visual feedback tool” — Simple Commenter’s MCP is real; the products optimize for different loops.',
            ],
            'faq' => [
                [
                    'q' => 'Doesn’t Simple Commenter already have MCP?',
                    'a' => 'Yes — agents can list comments, fix code, and update status. ReviseMy’s MCP is shaped around a design checkup loop: create_review, work_packets.pins, next_action, and a human verify gate. Different contract, overlapping audience.',
                ],
                [
                    'q' => 'Is ReviseMy a live-site widget?',
                    'a' => 'No. Reviewers open a secret review link (or MCP Apps inline UI) and mark captures. There is no embed script for production pages.',
                ],
                [
                    'q' => 'Can I use both?',
                    'a' => 'Yes. Simple Commenter for embedded client feedback on live sites; ReviseMy for structured agent checkups on captures across UI, email, and slides.',
                ],
            ],
            'related' => ['marker-io', 'workflow-design', 'pastel'],
        ],

        'ai-design-critique' => [
            'slug' => 'ai-design-critique',
            'path' => '/alternatives/ai-design-critique',
            'label' => 'AI chat apps',
            'competitor' => 'AI chat apps',
            'competitor_links' => [
                ['label' => 'ChatGPT', 'url' => '/for/chatgpt'],
                ['label' => 'Claude', 'url' => '/for/claude'],
                ['label' => 'Copilot', 'url' => '/for/copilot'],
                ['label' => 'Cursor', 'url' => '/for/cursor'],
                ['label' => 'Grok', 'url' => '/for/grok'],
            ],
            'teaser' => 'Instant vision opinions vs human marks that decide the loop.',
            'icon' => 'sparkles',
            'title' => 'Best alternative to just using an AI chat app — ReviseMy',
            'description' => 'Past pasting screenshots into ChatGPT or Claude: AI hints stay a second opinion, your marks decide, and your agent gets a board and next_action over MCP.',
            'keywords' => [
                'AI chat app alternative',
                'ChatGPT UI review alternative',
                'Claude vision design feedback',
                'human in the loop design review',
                'second opinion design hints',
            ],
            'headline' => 'Best alternative to just using an AI chat app',
            'subheadline' => 'Paste a screenshot into ChatGPT, Claude, Copilot, Cursor, or Grok and you get opinions. ReviseMy keeps AI as second opinion — humans mark, approve, and own the agent’s next_action.',
            'compare' => [
                'ending' => 'chat',
                'note' => 'Headline says what we are, not what you get. Lead with the subscription.',
                'them_end' => 'The opinions are the model’s, and nothing tracks which point got fixed.',
                'us_end' => 'Your mark stays the brief across passes, and you verify each fix.',
            ],
            'why_look' => [
                'Chat critiques vanish; agents re-invent the brief every pass.',
                'You need human must-fix / keep intent that overrides model confidence.',
                'Overlapping AI findings should enrich a mark — not invent conflicting must-fixes.',
                'You want Refresh second opinion without flipping approve / request-changes.',
            ],
            'what_to_look_for' => [
                'Whether AI output is labeled as suggestions only',
                'Whether humans remain the only deciders',
                'Whether agents get structured next_action instead of prose',
                'Whether checklist runs without an API key and vision is optional BYOK',
            ],
            'recommended' => [
                [
                    'id' => 'figma-comments',
                    'label' => 'Figma comments',
                    'href' => '/alternatives/figma-comments',
                    'badge' => null,
                    'summary' => 'Human critique on design files — still the right surface before pixels exist in the product.',
                    'best_for' => 'Pre-build design critique without an agent loop.',
                    'bullets' => [
                        'Native to design files',
                        'Great for systems and craft',
                        'Not an MCP agent handoff',
                    ],
                ],
            ],
            'keep_theirs' => [
                'Keep ChatGPT/Claude critique for quick taste brainstorms and learning prompts.',
                'Move to ReviseMy when you need persistence, authority, and an agent that follows next_action.',
                'You can paste a screenshot for a quick opinion, then open a ReviseMy review for the real pass.',
                'If you only ever want ephemeral chat advice and no ship gate, stick with an AI chat app.',
            ],
            'faq' => [
                [
                    'q' => 'Does ReviseMy still use AI?',
                    'a' => 'Yes, optionally. A free checklist always runs; vision needs your own API key. Both are second opinion — never approve/request-changes.',
                ],
                [
                    'q' => 'Can the agent ignore second opinion?',
                    'a' => 'Agents should treat second_opinion as hints and prioritize work_packets.pins. That is the product contract.',
                ],
                [
                    'q' => 'Where do craft lenses come from?',
                    'a' => 'See the second opinion page — published craft sources distilled into hints, not celebrity endorsements of your UI.',
                ],
            ],
            'related' => ['figma-comments', 'marker-io', 'pastel'],
        ],

    ],

];
